# Generated by Django 4.1.4 on 2022-12-27 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=15)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('number_of_tasks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=60)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookmarks.groups')),
            ],
        ),
    ]
