# Generated by Django 4.1.4 on 2022-12-27 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ['creation_date']},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['creation_date']},
        ),
        migrations.AlterField(
            model_name='groups',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, help_text='Exact time of creation of this group'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_name',
            field=models.CharField(help_text='Few words to describe the type of tasks inside of the group', max_length=15),
        ),
        migrations.AlterField(
            model_name='groups',
            name='number_of_tasks',
            field=models.IntegerField(default=0, help_text='Number of tasks inside the group, default is 0 after creating a group'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, help_text='Exact time of adding this task to the group'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateTimeField(help_text='Deadline of this task, not obligatory, default null', null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='group',
            field=models.ForeignKey(help_text='Group to which this task belongs', on_delete=django.db.models.deletion.CASCADE, to='Bookmarks.groups'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='is_finished',
            field=models.BooleanField(default=False, help_text='This field indicates if task is finished'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task',
            field=models.CharField(help_text='content of the task to be done', max_length=60),
        ),
    ]
