# Generated by Django 4.1.4 on 2022-12-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmarks', '0004_alter_tasks_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateTimeField(blank=True, default=None, help_text='Deadline of this task, not obligatory, default null'),
        ),
    ]
